--liquibase formatted sql

--changeset mcp-panel:003-users dbms:postgresql
--comment: users tablosu ve 2 indeksi

CREATE TABLE users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  full_name     text NOT NULL,
  password_hash text,                          -- NULL for a user who arrived through SSO
  role          user_role   NOT NULL DEFAULT 'viewer',
  status        user_status NOT NULL DEFAULT 'invited',
  team_id       bigint REFERENCES teams(id) ON DELETE SET NULL,
  avatar_url    text,
  -- Notification, language and theme preferences. The shape changes often and is never queried.
  preferences   jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_unique ON users (lower(email));

CREATE INDEX users_team_idx ON users (team_id);

--rollback DROP TABLE IF EXISTS users;
