--liquibase formatted sql

--changeset mcp-panel:006-secrets dbms:postgresql
--comment: secrets tablosu

-- Secrets are stored encrypted; decryption happens in the application, through KMS.
CREATE TABLE secrets (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  kind         secret_kind NOT NULL DEFAULT 'other',
  ciphertext   bytea NOT NULL,                 -- NEVER plain text
  key_id       text NOT NULL,                  -- the KMS key it was sealed with
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_name_unique UNIQUE (name)
);

--rollback DROP TABLE IF EXISTS secrets;
