--liquibase formatted sql

--changeset mcp-panel:008-host_groups dbms:postgresql
--comment: host_groups tablosu ve 1 indeksi

-- =============================================================================
-- 3. Sunucu envanteri
-- =============================================================================
-- A group is nothing but a list of addresses. Separate `hosts` and
-- `host_group_members` tables are not needed; the list is read and written with its owner.

CREATE TABLE host_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  -- ["web-01.internal", "web-02.internal", …]
  hosts       jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT host_groups_name_unique UNIQUE (name),
  CONSTRAINT host_groups_hosts_array CHECK (jsonb_typeof(hosts) = 'array')
);

-- For the question "which groups is this address in?"
CREATE INDEX host_groups_hosts_idx ON host_groups USING gin (hosts);

--rollback DROP TABLE IF EXISTS host_groups;
