--liquibase formatted sql

--changeset mcp-panel:009-definitions dbms:postgresql
--comment: definitions tablosu ve 2 indeksi

-- =============================================================================
-- 4. Definitions and actions
-- =============================================================================

-- One definition = ONE tool, as the MCP server exposes it.
CREATE TABLE definitions (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             text NOT NULL,
  -- The identity and description seen in the tools/list response
  tool_name        text NOT NULL,
  tool_description text NOT NULL DEFAULT '',
  model_id         bigint REFERENCES ai_models(id) ON DELETE RESTRICT,
  system_prompt    text NOT NULL DEFAULT '',

  -- Dynamic inputs. They do two jobs: they are the source of the {{placeholder}}
  -- values in an action's templates, and the tool's JSON Schema.
  -- [{ "key": "version", "label": "Version tag", "type": "text",
  --    "required": true, "defaultValue": "v2.4.0", "placeholder": "",
  --    "options": [] }, …]
  inputs           jsonb NOT NULL DEFAULT '[]'::jsonb,

  enabled          boolean NOT NULL DEFAULT true,
  created_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT definitions_name_unique UNIQUE (name),
  CONSTRAINT definitions_tool_name_unique UNIQUE (tool_name),
  -- The shape of an MCP tool name
  CONSTRAINT definitions_tool_name_format
    CHECK (tool_name ~ '^[a-z_][a-z0-9_]*$'),
  CONSTRAINT definitions_inputs_array CHECK (jsonb_typeof(inputs) = 'array')
);

CREATE INDEX definitions_model_idx ON definitions (model_id);

CREATE INDEX definitions_enabled_idx ON definitions (enabled);

--rollback DROP TABLE IF EXISTS definitions;
