--liquibase formatted sql

--changeset mcp-panel:010-actions dbms:postgresql
--comment: actions tablosu ve 3 indeksi

-- Actions stay a table of their own: they are ordered, added and removed one at a
-- time, and `runs` points at a row here. Type-specific settings live in `config`.
CREATE TABLE actions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  kind          action_kind NOT NULL,
  name          text NOT NULL,
  description   text NOT NULL DEFAULT '',
  position      integer NOT NULL DEFAULT 0,

  -- Everything that varies by type. The shape is in DATABASE.md.
  --   rest → method, url, headers[], body, timeoutMs
  --   ssh  → targetMode, host, hosts[], strategy, auth, commandMode, command,
  --          allowedCommands[], blockedPatterns[], sudo …
  --   db   → engine, host, port, database, queryMode, query, schemaHint,
  --          allowedOperations[], maxRows, readOnly …
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- The group target is a real column rather than JSONB: the delete behaviour and
  -- the "who uses this group" query both depend on it.
  host_group_id bigint REFERENCES host_groups(id) ON DELETE SET NULL,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT actions_config_object CHECK (jsonb_typeof(config) = 'object'),
  -- A group target only means anything for an SSH action
  CONSTRAINT actions_group_only_ssh
    CHECK (host_group_id IS NULL OR kind = 'ssh')
);

CREATE INDEX actions_definition_idx ON actions (definition_id, position);

CREATE INDEX actions_group_idx ON actions (host_group_id);

-- For finding a secret id or a blocked pattern inside config.
CREATE INDEX actions_config_idx ON actions USING gin (config);

--rollback DROP TABLE IF EXISTS actions;
