--liquibase formatted sql

--changeset mcp-panel:012-run_targets dbms:postgresql
--comment: run_targets tablosu ve 1 indeksi

-- A table of its own: across ten servers each target moves at its own pace and its
-- row is updated individually. Doing that inside a JSONB array would mean locks and
-- write conflicts.
CREATE TABLE run_targets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id         bigint NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  address        text NOT NULL,
  batch_index    integer NOT NULL DEFAULT 0,   -- which round, under the rolling strategy
  status         target_status NOT NULL DEFAULT 'pending',
  exit_code      integer,
  duration_ms    integer,
  stdout_excerpt text,
  stderr_excerpt text,
  started_at     timestamptz,
  finished_at    timestamptz,
  CONSTRAINT run_targets_unique UNIQUE (run_id, address)
);

CREATE INDEX run_targets_run_idx ON run_targets (run_id, batch_index);

--rollback DROP TABLE IF EXISTS run_targets;
