--liquibase formatted sql

--changeset mcp-panel:018-conversations dbms:postgresql
--comment: the console's conversation history

-- Console turns lived only in the browser's memory: leaving the page lost the sentence
-- somebody asked, which tool the model chose and why, and the plan it produced — all
-- at once. Executed work is already in `runs`; what went missing was the conversation
-- itself, and the attempts made with the box unticked, which produce no run at all.
CREATE TABLE conversations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_ref text NOT NULL,
  owner_id         bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title            text NOT NULL DEFAULT '',
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversations_ref_unique UNIQUE (conversation_ref)
);

-- A conversation belongs to its owner: the sentences carry business detail and are not
-- shared by default. The list is always read as "my conversations, newest first", so
-- the index carries that order.
CREATE INDEX conversations_owner_idx ON conversations (owner_id, updated_at DESC);

CREATE TABLE conversation_turns (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  prompt          text NOT NULL,
  -- The tool the operator pinned; empty means the model chose. What the model chose is
  -- in tool_name — two different questions, so two columns.
  pinned_tool     text,
  tool_name       text,
  executed        boolean NOT NULL DEFAULT false,
  status          text,
  reasoning       text,
  problem         text,
  statement       text,
  -- A pointer at the output, not a copy of it. One copy on purpose: two would mean two
  -- places to look for personal data that has to be deleted. A turn dispatches one job
  -- (dispatch.run_id), so this is singular.
  run_ref         text,
  failure         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX conversation_turns_conversation_idx ON conversation_turns (conversation_id, id);

--rollback DROP TABLE IF EXISTS conversation_turns;
--rollback DROP TABLE IF EXISTS conversations;
