-- =============================================================================
-- MCP Panel — the PostgreSQL schema
-- Hedef: PostgreSQL 10+ (GENERATED … AS IDENTITY)
-- =============================================================================
-- Application guide: docs/PANEL.md · Schema guide: docs/DATABASE.md
--
-- The panel is the CONTROL PLANE for the MCP server. The MCP server itself is a
-- separate application (Python) and reads this schema:
--   tools/list  → the definitions rows where enabled = true
--   tools/call  → that definition's model_id, system_prompt and actions
--
-- -----------------------------------------------------------------------------
-- The design rule: JSONB or a table?
-- -----------------------------------------------------------------------------
--   JSONB  → configuration. Always read and written with its owner, changed
--            all at once, never queried a row at a time.
--            (action settings, input definitions, model parameters, group
--            members, the values a run was given)
--
--   TABLE  → state that changes on its own, and records that accumulate. Rows
--            are updated one at a time, or pile up and get queried.
--            (users, models, definitions, actions, run targets, call logs,
--            the audit trail)
--
-- The result: 13 tables, 9 enums. No `sessions` table — sessions live in Redis.
--
-- The exact shape of each JSONB column is in DATABASE.md → "JSON shapes".
--
-- There are NO stored procedures, functions or triggers here — only types, tables
-- and indexes. The application writes `updated_at` (Hibernate's @UpdateTimestamp on
-- the Spring side); on INSERT the column default takes over.
--
-- Birincil anahtarlar `bigint GENERATED BY DEFAULT AS IDENTITY`. "BY DEFAULT",
-- Preferred over ALWAYS: a migration or a seed load has to be able to write an
-- explicit id. The Hibernate equivalent is @GeneratedValue(strategy = IDENTITY).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Enum tipleri
-- Only what real columns use is an enum. The distinctions inside JSONB — HTTP
-- method, SSH auth method, query mode and so on — stay as plain text and are
-- validated by the application.
-- -----------------------------------------------------------------------------

CREATE TYPE user_role      AS ENUM ('admin', 'developer', 'viewer');
CREATE TYPE user_status    AS ENUM ('active', 'invited', 'suspended');
CREATE TYPE model_provider AS ENUM ('anthropic', 'openai_compatible', 'azure',
                                    'vertex', 'bedrock', 'ollama', 'custom');
CREATE TYPE model_status   AS ENUM ('online', 'degraded', 'offline', 'unchecked');
CREATE TYPE action_kind    AS ENUM ('rest', 'ssh', 'db');
CREATE TYPE log_level      AS ENUM ('info', 'warn', 'error');
CREATE TYPE run_status     AS ENUM ('pending', 'awaiting_approval', 'running',
                                    'succeeded', 'failed', 'cancelled');
CREATE TYPE target_status  AS ENUM ('pending', 'running', 'succeeded',
                                    'failed', 'skipped');
CREATE TYPE secret_kind    AS ENUM ('ssh_private_key', 'ssh_passphrase',
                                    'password', 'api_token', 'model_api_key',
                                    'other');

-- =============================================================================
-- 1. Identity and access
-- =============================================================================
-- Sessions are in Redis. What is here is the durable identity records.

CREATE TABLE teams (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT teams_name_unique UNIQUE (name)
);

CREATE TABLE users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  full_name     text NOT NULL,
  password_hash text,                          -- NULL for a user who arrived through SSO
  role          user_role   NOT NULL DEFAULT 'viewer',
  status        user_status NOT NULL DEFAULT 'invited',
  team_id       bigint REFERENCES teams(id) ON DELETE SET NULL,
  avatar_url    text,
  -- Notification, language and theme preferences. The shape changes often and is
  preferences   jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_unique ON users (lower(email));
CREATE INDEX users_team_idx ON users (team_id);

CREATE TABLE user_invitations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       text NOT NULL,
  role        user_role NOT NULL DEFAULT 'viewer',
  team_id     bigint REFERENCES teams(id) ON DELETE SET NULL,
  token_hash  text NOT NULL,
  invited_by  bigint REFERENCES users(id) ON DELETE SET NULL,
  expires_at  timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_invitations_token_unique UNIQUE (token_hash)
);

CREATE INDEX user_invitations_email_idx ON user_invitations (lower(email));

CREATE TABLE api_keys (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  key_prefix   text NOT NULL,                  -- "mcp_live_9f3c" — shown in the list
  key_hash     text NOT NULL,                  -- the full key exists only as a hash
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_keys_hash_unique UNIQUE (key_hash)
);

CREATE INDEX api_keys_active_idx ON api_keys (revoked_at) WHERE revoked_at IS NULL;

-- Secrets are stored encrypted; decryption happens in the application, through KMS.
CREATE TABLE secrets (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  kind         secret_kind NOT NULL DEFAULT 'other',
  ciphertext   bytea NOT NULL,                 -- NEVER plain text
  key_id       text NOT NULL,                  -- the KMS key it was sealed with
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_name_unique UNIQUE (name)
);

-- =============================================================================
-- 2. AI modelleri
-- =============================================================================

CREATE TABLE ai_models (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,             -- "Claude Opus 5 — production"
  provider          model_provider NOT NULL DEFAULT 'anthropic',
  model_id          text NOT NULL,             -- "claude-opus-5"
  endpoint          text NOT NULL,             -- "https://api.anthropic.com"
  api_key_secret_id bigint REFERENCES secrets(id) ON DELETE RESTRICT,

  -- Request parameters. JSONB because the fields differ by provider:
  --   anthropic → { "maxTokens": 16000, "effort": "high",
  --                 "thinking": "adaptive", "timeoutMs": 600000 }
  --   others    → { "maxTokens": 4096, "temperature": 0.7, "timeoutMs": 120000 }
  params            jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- The result of the last connection attempt:
  --   { "status": "online", "latencyMs": 820,
  --     "checkedAt": "2026-08-20T09:41:00Z", "error": null }
  health            jsonb NOT NULL DEFAULT '{}'::jsonb,

  enabled           boolean NOT NULL DEFAULT true,
  notes             text NOT NULL DEFAULT '',
  created_by        bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ai_models_name_unique UNIQUE (name),
  CONSTRAINT ai_models_params_object CHECK (jsonb_typeof(params) = 'object'),
  CONSTRAINT ai_models_health_object CHECK (jsonb_typeof(health) = 'object'),
  -- temperature/top_p were removed in Claude 4.6 and later; sending them is a 400.
  -- The schema enforces that on the JSONB as well.
  CONSTRAINT ai_models_no_temperature_on_anthropic
    CHECK (provider <> 'anthropic' OR NOT (params ? 'temperature'))
);

CREATE INDEX ai_models_enabled_idx ON ai_models (enabled);
-- The panel filters on status; an expression index over the JSONB field is enough.
CREATE INDEX ai_models_status_idx ON ai_models ((health ->> 'status'));

-- =============================================================================
-- 3. Sunucu envanteri
-- =============================================================================
-- A group is nothing but a list of addresses. Separate `hosts` and
-- `host_group_members` tables are not needed; the list is read and written with its owner.

CREATE TABLE host_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  -- ["web-01.internal", "web-02.internal", …]
  hosts       jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT host_groups_name_unique UNIQUE (name),
  CONSTRAINT host_groups_hosts_array CHECK (jsonb_typeof(hosts) = 'array')
);

-- For the question "which groups is this address in?"
CREATE INDEX host_groups_hosts_idx ON host_groups USING gin (hosts);

-- =============================================================================
-- 4. Definitions and actions
-- =============================================================================

-- One definition = ONE tool, as the MCP server exposes it.
CREATE TABLE definitions (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             text NOT NULL,
  -- The identity and description seen in the tools/list response
  tool_name        text NOT NULL,
  tool_description text NOT NULL DEFAULT '',
  model_id         bigint REFERENCES ai_models(id) ON DELETE RESTRICT,
  system_prompt    text NOT NULL DEFAULT '',

  -- Dynamic inputs. They do two jobs: they are the source of the {{placeholder}}
  -- values in an action's templates, and the tool's JSON Schema.
  -- [{ "key": "version", "label": "Version tag", "type": "text",
  --    "required": true, "defaultValue": "v2.4.0", "placeholder": "",
  --    "options": [] }, …]
  inputs           jsonb NOT NULL DEFAULT '[]'::jsonb,

  enabled          boolean NOT NULL DEFAULT true,
  created_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT definitions_name_unique UNIQUE (name),
  CONSTRAINT definitions_tool_name_unique UNIQUE (tool_name),
  -- The shape of an MCP tool name
  CONSTRAINT definitions_tool_name_format
    CHECK (tool_name ~ '^[a-z_][a-z0-9_]*$'),
  CONSTRAINT definitions_inputs_array CHECK (jsonb_typeof(inputs) = 'array')
);

CREATE INDEX definitions_model_idx ON definitions (model_id);
CREATE INDEX definitions_enabled_idx ON definitions (enabled);

-- Actions stay a table of their own: they are ordered, added and removed one at a
-- time, and `runs` points at a row here. Type-specific settings live in `config`.
CREATE TABLE actions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  kind          action_kind NOT NULL,
  name          text NOT NULL,
  description   text NOT NULL DEFAULT '',
  position      integer NOT NULL DEFAULT 0,

  -- Everything that varies by type. The shape is in DATABASE.md.
  --   rest → method, url, headers[], body, timeoutMs
  --   ssh  → targetMode, host, hosts[], strategy, auth, commandMode, command,
  --          allowedCommands[], blockedPatterns[], sudo …
  --   db   → engine, host, port, database, queryMode, query, schemaHint,
  --          allowedOperations[], maxRows, readOnly …
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- The group target is a real column rather than JSONB: the delete behaviour and
  -- the "who uses this group" query both depend on it.
  host_group_id bigint REFERENCES host_groups(id) ON DELETE SET NULL,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT actions_config_object CHECK (jsonb_typeof(config) = 'object'),
  -- A group target only means anything for an SSH action
  CONSTRAINT actions_group_only_ssh
    CHECK (host_group_id IS NULL OR kind = 'ssh')
);

CREATE INDEX actions_definition_idx ON actions (definition_id, position);
CREATE INDEX actions_group_idx ON actions (host_group_id);
-- For finding a secret id or a blocked pattern inside config.
CREATE INDEX actions_config_idx ON actions USING gin (config);

-- =============================================================================
-- 5. Runs and auditing
-- =============================================================================

CREATE TABLE runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  action_id     bigint REFERENCES actions(id) ON DELETE SET NULL,
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text,                          -- non-human callers, such as "agent:ci-bot"
  status        run_status NOT NULL DEFAULT 'pending',

  -- The input values the run was given. Secret-typed ones are left null:
  --   { "surum": "v2.4.0", "ortam": "production", "deploy_token": null }
  inputs        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- In dynamic mode, the text the model wrote — kept for the audit trail.
  generated_command text,
  generated_query   text,
  approved_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  approved_at   timestamptz,

  started_at    timestamptz,
  finished_at   timestamptz,
  error         text,
  created_at    timestamptz NOT NULL DEFAULT now(),

  -- References mcp-action generates itself: run_ref per job, action_ref per action.
  -- Without them there is no telling which row an incoming result belongs to —
  -- runs.id is a bigint identity and the executor never sees it.
  run_ref       text,
  action_ref    text,
  -- Why the run happened: work somebody asked for ('execute'), or something this
  -- service asked for itself ('introspect'). The result arrives the same way either way.
  purpose       text NOT NULL DEFAULT 'execute',

  CONSTRAINT runs_inputs_object CHECK (jsonb_typeof(inputs) = 'object')
);

CREATE INDEX runs_definition_idx ON runs (definition_id, created_at DESC);
-- One row is looked up when a result arrives, so this is unique. Partial, because
-- older rows without a reference are all NULL and must not block each other.
CREATE UNIQUE INDEX runs_action_ref_unique ON runs (action_ref) WHERE action_ref IS NOT NULL;
CREATE INDEX runs_run_ref_idx ON runs (run_ref) WHERE run_ref IS NOT NULL;
CREATE INDEX runs_status_idx ON runs (status)
  WHERE status IN ('pending', 'running', 'awaiting_approval');

-- A table of its own: across ten servers each target moves at its own pace and its
-- row is updated individually. Doing that inside a JSONB array would mean locks and
-- write conflicts.
CREATE TABLE run_targets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id         bigint NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  address        text NOT NULL,
  batch_index    integer NOT NULL DEFAULT 0,   -- which round, under the rolling strategy
  status         target_status NOT NULL DEFAULT 'pending',
  exit_code      integer,
  duration_ms    integer,
  -- Sema okumasinin ciktisi burada, acik: donen sey tablo tanimi, kimsenin verisi
  -- degil, ve planlayici onu acik metin okumak zorunda. 019'dan onceki calistirma
  -- ciktilari da burada duruyor.
  stdout_excerpt text,
  stderr_excerpt text,                         -- hata aciklamasi; muhurlenmez
  result_rows    jsonb,                        -- 019 oncesi sorgu sonucu
  -- Calistirma ciktisi, mcp-cipher ile muhurlu: metin ve satirlar tek zarfta.
  -- Anahtar bu veritabaninin disinda, yani veritabaninin kopyasi verinin kopyasi degil.
  output_sealed  bytea,
  output_key_id  text,
  started_at     timestamptz,
  finished_at    timestamptz,
  CONSTRAINT run_targets_unique UNIQUE (run_id, address)
);

CREATE INDEX run_targets_run_idx ON run_targets (run_id, batch_index);

-- Konsol sohbetleri. Turlar tarayicinin belleginde duruyordu: sayfadan cikan
-- kullanici sordugu cumleyi, modelin gerekcesini ve plani birlikte kaybediyordu,
-- ve kutu isaretsizken hic run kaydi olusmuyor.
CREATE TABLE conversations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_ref text NOT NULL,
  owner_id         bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title            text NOT NULL DEFAULT '',   -- ilk sorudan turetilir
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversations_ref_unique UNIQUE (conversation_ref)
);

CREATE INDEX conversations_owner_idx ON conversations (owner_id, updated_at DESC);

CREATE TABLE conversation_turns (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  prompt          text NOT NULL,
  pinned_tool     text,                        -- operatorun sabitledigi arac
  tool_name       text,                        -- cevabi veren arac
  executed        boolean NOT NULL DEFAULT false,
  status          text,
  reasoning       text,
  problem         text,
  statement       text,
  run_ref         text,                        -- ciktinin kopyasi degil, isaretcisi
  failure         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX conversation_turns_conversation_idx ON conversation_turns (conversation_id, id);

-- Tool call records — these feed the panel's /logs page
CREATE TABLE tool_calls (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint REFERENCES definitions(id) ON DELETE SET NULL,
  tool_name     text NOT NULL,                 -- so the record still reads after the definition is gone
  model_id      bigint REFERENCES ai_models(id) ON DELETE SET NULL,
  model_label   text NOT NULL DEFAULT '',      -- "claude-opus-5"
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text NOT NULL,
  run_id        bigint REFERENCES runs(id) ON DELETE SET NULL,
  level         log_level NOT NULL DEFAULT 'info',
  duration_ms   integer NOT NULL DEFAULT 0,
  input_tokens  integer,
  output_tokens integer,
  message       text NOT NULL DEFAULT '',
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tool_calls_recent_idx ON tool_calls (created_at DESC);
CREATE INDEX tool_calls_definition_idx ON tool_calls (definition_id, created_at DESC);
CREATE INDEX tool_calls_model_idx ON tool_calls (model_id, created_at DESC);
CREATE INDEX tool_calls_level_idx ON tool_calls (level, created_at DESC);

-- The general audit trail — feeds the "Recent activity" stream in the panel
CREATE TABLE audit_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label text NOT NULL,
  action      text NOT NULL,                   -- "definition.created"
  entity_type text NOT NULL,                   -- "definition"
  entity_id   bigint,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_events_recent_idx ON audit_events (created_at DESC);
CREATE INDEX audit_events_entity_idx ON audit_events (entity_type, entity_id);

COMMIT;
