-- =============================================================================
-- MCP Panel — PostgreSQL şeması
-- Hedef: PostgreSQL 10+ (GENERATED … AS IDENTITY)
-- =============================================================================
-- Uygulama dokümanı: docs/PANEL.md · Şema dokümanı: docs/DATABASE.md
--
-- Panel, MCP sunucusunun KONTROL DÜZLEMİDİR. MCP sunucusunun kendisi ayrı bir
-- uygulamadır (Python) ve bu şemayı okur:
--   tools/list  → enabled = true olan definitions satırları
--   tools/call  → tanımın model_id'si, system_prompt'u ve actions'ları
--
-- -----------------------------------------------------------------------------
-- Tasarım kuralı: JSONB mi, tablo mu?
-- -----------------------------------------------------------------------------
--   JSONB  → yapılandırma. Her zaman sahibiyle birlikte okunur/yazılır, tek
--            işlemde tümü değişir, tekil satırına bağımsız sorgu atılmaz.
--            (aksiyon ayarları, girdi tanımları, model parametreleri, grup
--            üyeleri, çalıştırmaya geçilen değerler)
--
--   TABLO  → bağımsız değişen durum ve büyüyen kayıt. Satırları tek tek
--            güncellenir ya da zamanla birikip sorgulanır.
--            (kullanıcılar, modeller, tanımlar, aksiyonlar, çalıştırma
--            hedefleri, çağrı kayıtları, denetim izi)
--
-- Sonuç: 13 tablo, 9 enum. Oturumlar Redis'te tutulduğu için `sessions` yok.
--
-- JSONB kolonlarının tam şekli DATABASE.md → "JSON şekilleri" bölümünde.
--
-- Bu dosyada saklı yordam, fonksiyon ya da trigger YOKTUR — yalnızca tip, tablo
-- ve indeks tanımları. `updated_at` kolonlarını uygulama yazar (Spring tarafında
-- Hibernate `@UpdateTimestamp`); INSERT sırasında kolon varsayılanı devreye girer.
--
-- Birincil anahtarlar `bigint GENERATED BY DEFAULT AS IDENTITY`. "BY DEFAULT",
-- "ALWAYS"a tercih edildi: veri taşımada ve tohum yüklemede açık kimlik
-- yazılabilmesi gerekiyor. Hibernate karşılığı @GeneratedValue(strategy = IDENTITY).
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Enum tipleri
-- Yalnızca gerçek kolonlarda kullanılanlar enum. JSONB içindeki ayrımlar
-- (http metodu, ssh kimlik yöntemi, sorgu biçimi …) düz metin olarak durur ve
-- uygulama tarafında doğrulanır.
-- -----------------------------------------------------------------------------

CREATE TYPE user_role      AS ENUM ('admin', 'developer', 'viewer');
CREATE TYPE user_status    AS ENUM ('active', 'invited', 'suspended');
CREATE TYPE model_provider AS ENUM ('anthropic', 'openai_compatible', 'azure',
                                    'vertex', 'bedrock', 'ollama', 'custom');
CREATE TYPE model_status   AS ENUM ('online', 'degraded', 'offline', 'unchecked');
CREATE TYPE action_kind    AS ENUM ('rest', 'ssh', 'db');
CREATE TYPE log_level      AS ENUM ('info', 'warn', 'error');
CREATE TYPE run_status     AS ENUM ('pending', 'awaiting_approval', 'running',
                                    'succeeded', 'failed', 'cancelled');
CREATE TYPE target_status  AS ENUM ('pending', 'running', 'succeeded',
                                    'failed', 'skipped');
CREATE TYPE secret_kind    AS ENUM ('ssh_private_key', 'ssh_passphrase',
                                    'password', 'api_token', 'model_api_key',
                                    'other');

-- =============================================================================
-- 1. Kimlik ve erişim
-- =============================================================================
-- Oturumlar Redis'te. Burada yalnızca kalıcı kimlik kayıtları var.

CREATE TABLE teams (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT teams_name_unique UNIQUE (name)
);

CREATE TABLE users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         text NOT NULL,
  full_name     text NOT NULL,
  password_hash text,                          -- SSO ile gelen kullanıcıda NULL
  role          user_role   NOT NULL DEFAULT 'viewer',
  status        user_status NOT NULL DEFAULT 'invited',
  team_id       bigint REFERENCES teams(id) ON DELETE SET NULL,
  avatar_url    text,
  -- Bildirim, dil, tema gibi tercihler; şeması sık değişir, sorgulanmaz.
  preferences   jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_login_at timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_unique ON users (lower(email));
CREATE INDEX users_team_idx ON users (team_id);

CREATE TABLE user_invitations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       text NOT NULL,
  role        user_role NOT NULL DEFAULT 'viewer',
  team_id     bigint REFERENCES teams(id) ON DELETE SET NULL,
  token_hash  text NOT NULL,
  invited_by  bigint REFERENCES users(id) ON DELETE SET NULL,
  expires_at  timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT user_invitations_token_unique UNIQUE (token_hash)
);

CREATE INDEX user_invitations_email_idx ON user_invitations (lower(email));

CREATE TABLE api_keys (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  key_prefix   text NOT NULL,                  -- "mcp_live_9f3c" — listede gösterilir
  key_hash     text NOT NULL,                  -- tam anahtar yalnızca hash olarak
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  revoked_at   timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_keys_hash_unique UNIQUE (key_hash)
);

CREATE INDEX api_keys_active_idx ON api_keys (revoked_at) WHERE revoked_at IS NULL;

-- Sırlar şifreli saklanır; çözme uygulama tarafında KMS/vault ile yapılır.
CREATE TABLE secrets (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  kind         secret_kind NOT NULL DEFAULT 'other',
  ciphertext   bytea NOT NULL,                 -- ASLA düz metin
  key_id       text NOT NULL,                  -- şifrelemede kullanılan KMS anahtarı
  created_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  last_used_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT secrets_name_unique UNIQUE (name)
);

-- =============================================================================
-- 2. AI modelleri
-- =============================================================================

CREATE TABLE ai_models (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name              text NOT NULL,             -- "Claude Opus 5 — üretim"
  provider          model_provider NOT NULL DEFAULT 'anthropic',
  model_id          text NOT NULL,             -- "claude-opus-5"
  endpoint          text NOT NULL,             -- "https://api.anthropic.com"
  api_key_secret_id bigint REFERENCES secrets(id) ON DELETE RESTRICT,

  -- İstek parametreleri. Sağlayıcıya göre alanlar değiştiği için JSONB:
  --   anthropic → { "maxTokens": 16000, "effort": "high",
  --                 "thinking": "adaptive", "timeoutMs": 600000 }
  --   diğerleri → { "maxTokens": 4096, "temperature": 0.7, "timeoutMs": 120000 }
  params            jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Son bağlantı denemesinin sonucu:
  --   { "status": "online", "latencyMs": 820,
  --     "checkedAt": "2026-08-20T09:41:00Z", "error": null }
  health            jsonb NOT NULL DEFAULT '{}'::jsonb,

  enabled           boolean NOT NULL DEFAULT true,
  notes             text NOT NULL DEFAULT '',
  created_by        bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ai_models_name_unique UNIQUE (name),
  CONSTRAINT ai_models_params_object CHECK (jsonb_typeof(params) = 'object'),
  CONSTRAINT ai_models_health_object CHECK (jsonb_typeof(health) = 'object'),
  -- Claude 4.6+ modellerinde temperature/top_p kaldırıldı; gönderilirse 400.
  -- Şema bunu JSONB üzerinde de zorlar.
  CONSTRAINT ai_models_no_temperature_on_anthropic
    CHECK (provider <> 'anthropic' OR NOT (params ? 'temperature'))
);

CREATE INDEX ai_models_enabled_idx ON ai_models (enabled);
-- Durum panelde filtrelenir; JSONB alanı üzerinden ifade indeksi yeterli.
CREATE INDEX ai_models_status_idx ON ai_models ((health ->> 'status'));

-- =============================================================================
-- 3. Sunucu envanteri
-- =============================================================================
-- Grup, adres listesinden ibaret. Ayrı `hosts` + `host_group_members`
-- tablolarına gerek yok; liste sahibiyle birlikte okunup yazılıyor.

CREATE TABLE host_groups (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  -- ["web-01.internal", "web-02.internal", …]
  hosts       jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT host_groups_name_unique UNIQUE (name),
  CONSTRAINT host_groups_hosts_array CHECK (jsonb_typeof(hosts) = 'array')
);

-- "Bu adres hangi gruplarda?" sorusu için.
CREATE INDEX host_groups_hosts_idx ON host_groups USING gin (hosts);

-- =============================================================================
-- 4. Tanımlar ve aksiyonlar
-- =============================================================================

-- Bir tanım = MCP sunucusunun dışarı açtığı BİR araç.
CREATE TABLE definitions (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name             text NOT NULL,
  -- tools/list yanıtında görünen kimlik ve açıklama
  tool_name        text NOT NULL,
  tool_description text NOT NULL DEFAULT '',
  model_id         bigint REFERENCES ai_models(id) ON DELETE RESTRICT,
  system_prompt    text NOT NULL DEFAULT '',

  -- Dinamik girdiler. İki işi birden görür: aksiyon şablonlarındaki
  -- {{yer_tutucu}} kaynağı ve aracın JSON Schema'sı.
  -- [{ "key": "surum", "label": "Sürüm etiketi", "type": "text",
  --    "required": true, "defaultValue": "v2.4.0", "placeholder": "",
  --    "options": [] }, …]
  inputs           jsonb NOT NULL DEFAULT '[]'::jsonb,

  enabled          boolean NOT NULL DEFAULT true,
  created_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  updated_by       bigint REFERENCES users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT definitions_name_unique UNIQUE (name),
  CONSTRAINT definitions_tool_name_unique UNIQUE (tool_name),
  -- MCP araç adı biçimi
  CONSTRAINT definitions_tool_name_format
    CHECK (tool_name ~ '^[a-z_][a-z0-9_]*$'),
  CONSTRAINT definitions_inputs_array CHECK (jsonb_typeof(inputs) = 'array')
);

CREATE INDEX definitions_model_idx ON definitions (model_id);
CREATE INDEX definitions_enabled_idx ON definitions (enabled);

-- Aksiyonlar ayrı tablo kalıyor: sıralanır, tek tek silinir/eklenir ve
-- `runs` buradan bir satıra işaret eder. Tipe özgü ayarlar `config` içinde.
CREATE TABLE actions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  kind          action_kind NOT NULL,
  name          text NOT NULL,
  description   text NOT NULL DEFAULT '',
  position      integer NOT NULL DEFAULT 0,

  -- Tipe göre değişen tüm ayarlar. Şekli DATABASE.md'de.
  --   rest → method, url, headers[], body, timeoutMs
  --   ssh  → targetMode, host, hosts[], strategy, auth, commandMode, command,
  --          allowedCommands[], blockedPatterns[], sudo …
  --   db   → engine, host, port, database, queryMode, query, schemaHint,
  --          allowedOperations[], maxRows, readOnly …
  config        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Grup hedefi JSONB'de değil gerçek kolonda: silme davranışı ve
  -- "bu grubu kim kullanıyor" sorgusu buna bağlı.
  host_group_id bigint REFERENCES host_groups(id) ON DELETE SET NULL,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT actions_config_object CHECK (jsonb_typeof(config) = 'object'),
  -- Grup hedefi yalnızca SSH aksiyonunda anlamlı
  CONSTRAINT actions_group_only_ssh
    CHECK (host_group_id IS NULL OR kind = 'ssh')
);

CREATE INDEX actions_definition_idx ON actions (definition_id, position);
CREATE INDEX actions_group_idx ON actions (host_group_id);
-- config içinde sır kimliği / yasak kalıp araması için.
CREATE INDEX actions_config_idx ON actions USING gin (config);

-- =============================================================================
-- 5. Çalıştırma ve denetim
-- =============================================================================

CREATE TABLE runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint NOT NULL REFERENCES definitions(id) ON DELETE CASCADE,
  action_id     bigint REFERENCES actions(id) ON DELETE SET NULL,
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text,                          -- "agent:ci-bot" gibi insan olmayan çağıranlar
  status        run_status NOT NULL DEFAULT 'pending',

  -- Çalıştırmaya geçilen girdi değerleri. Sır tipindekiler null bırakılır:
  --   { "surum": "v2.4.0", "ortam": "production", "deploy_token": null }
  inputs        jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- Dinamik modda modelin ürettiği metin — denetim için saklanır.
  generated_command text,
  generated_query   text,
  approved_by   bigint REFERENCES users(id) ON DELETE SET NULL,
  approved_at   timestamptz,

  started_at    timestamptz,
  finished_at   timestamptz,
  error         text,
  created_at    timestamptz NOT NULL DEFAULT now(),

  -- mcp-action'ın kendi ürettiği referanslar: iş başına run_ref, aksiyon başına
  -- action_ref. Bunlar olmadan gelen sonucun hangi satıra ait olduğu bilinemez —
  -- runs.id bir bigint identity ve executor onu hiç görmez.
  run_ref       text,
  action_ref    text,
  -- Çalıştırmanın sebebi: kullanıcının istediği iş ('execute') ya da bu servisin
  -- kendi sorduğu bir şey ('introspect'). Sonuç aynı kuyruktan aynı şekilde gelir.
  purpose       text NOT NULL DEFAULT 'execute',

  CONSTRAINT runs_inputs_object CHECK (jsonb_typeof(inputs) = 'object')
);

CREATE INDEX runs_definition_idx ON runs (definition_id, created_at DESC);
-- Sonuç geldiğinde tek satır aranır, o yüzden benzersiz. Kısmi indeks: referansı
-- olmayan eski satırların hepsi NULL ve birbirini engellememeli.
CREATE UNIQUE INDEX runs_action_ref_unique ON runs (action_ref) WHERE action_ref IS NOT NULL;
CREATE INDEX runs_run_ref_idx ON runs (run_ref) WHERE run_ref IS NOT NULL;
CREATE INDEX runs_status_idx ON runs (status)
  WHERE status IN ('pending', 'running', 'awaiting_approval');

-- Tablo kalıyor: 10 sunuculuk bir turda her hedef kendi hızında ilerler ve
-- satırı tek tek güncellenir. JSONB dizisinde bunu yapmak kilit ve yazma
-- çakışması demek olurdu.
CREATE TABLE run_targets (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id         bigint NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
  address        text NOT NULL,
  batch_index    integer NOT NULL DEFAULT 0,   -- rolling stratejide kaçıncı tur
  status         target_status NOT NULL DEFAULT 'pending',
  exit_code      integer,
  duration_ms    integer,
  -- Sema okumasinin ciktisi burada, acik: donen sey tablo tanimi, kimsenin verisi
  -- degil, ve planlayici onu acik metin okumak zorunda. 019'dan onceki calistirma
  -- ciktilari da burada duruyor.
  stdout_excerpt text,
  stderr_excerpt text,                         -- hata aciklamasi; muhurlenmez
  result_rows    jsonb,                        -- 019 oncesi sorgu sonucu
  -- Calistirma ciktisi, mcp-cipher ile muhurlu: metin ve satirlar tek zarfta.
  -- Anahtar bu veritabaninin disinda, yani veritabaninin kopyasi verinin kopyasi degil.
  output_sealed  bytea,
  output_key_id  text,
  started_at     timestamptz,
  finished_at    timestamptz,
  CONSTRAINT run_targets_unique UNIQUE (run_id, address)
);

CREATE INDEX run_targets_run_idx ON run_targets (run_id, batch_index);

-- Konsol sohbetleri. Turlar tarayicinin belleginde duruyordu: sayfadan cikan
-- kullanici sordugu cumleyi, modelin gerekcesini ve plani birlikte kaybediyordu,
-- ve kutu isaretsizken hic run kaydi olusmuyor.
CREATE TABLE conversations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_ref text NOT NULL,
  owner_id         bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title            text NOT NULL DEFAULT '',   -- ilk sorudan turetilir
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT conversations_ref_unique UNIQUE (conversation_ref)
);

CREATE INDEX conversations_owner_idx ON conversations (owner_id, updated_at DESC);

CREATE TABLE conversation_turns (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
  prompt          text NOT NULL,
  pinned_tool     text,                        -- operatorun sabitledigi arac
  tool_name       text,                        -- cevabi veren arac
  executed        boolean NOT NULL DEFAULT false,
  status          text,
  reasoning       text,
  problem         text,
  statement       text,
  run_ref         text,                        -- ciktinin kopyasi degil, isaretcisi
  failure         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX conversation_turns_conversation_idx ON conversation_turns (conversation_id, id);

-- Araç çağrısı kayıtları — panelde /logs sayfasını besler
CREATE TABLE tool_calls (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  definition_id bigint REFERENCES definitions(id) ON DELETE SET NULL,
  tool_name     text NOT NULL,                 -- tanım silinse de kayıt okunabilsin
  model_id      bigint REFERENCES ai_models(id) ON DELETE SET NULL,
  model_label   text NOT NULL DEFAULT '',      -- "claude-opus-5"
  actor_id      bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label   text NOT NULL,
  run_id        bigint REFERENCES runs(id) ON DELETE SET NULL,
  level         log_level NOT NULL DEFAULT 'info',
  duration_ms   integer NOT NULL DEFAULT 0,
  input_tokens  integer,
  output_tokens integer,
  message       text NOT NULL DEFAULT '',
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tool_calls_recent_idx ON tool_calls (created_at DESC);
CREATE INDEX tool_calls_definition_idx ON tool_calls (definition_id, created_at DESC);
CREATE INDEX tool_calls_model_idx ON tool_calls (model_id, created_at DESC);
CREATE INDEX tool_calls_level_idx ON tool_calls (level, created_at DESC);

-- Genel denetim izi — panelde "Son hareketler" akışını besler
CREATE TABLE audit_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id    bigint REFERENCES users(id) ON DELETE SET NULL,
  actor_label text NOT NULL,
  action      text NOT NULL,                   -- "definition.created"
  entity_type text NOT NULL,                   -- "definition"
  entity_id   bigint,
  metadata    jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX audit_events_recent_idx ON audit_events (created_at DESC);
CREATE INDEX audit_events_entity_idx ON audit_events (entity_type, entity_id);

COMMIT;
